import { StyleSheet } from "react-native";

export const styleschecklist = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f0f2f5',
        marginTop: -30,
    },
    // Sección fija superior
    fixedSection: {
        backgroundColor: '#f0f2f5',
        zIndex: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 5,
        paddingVertical: 4,
    },
    // ScrollView solo para áreas
    areasScrollView: {
        flex: 1,
        backgroundColor: '#f0f2f5',
        marginTop: 5,
    },
    scrollView: {
        flex: 1,
    },
    header: {
        paddingVertical: 1,
        paddingHorizontal: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    title: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'white',
        marginBottom: 5,
        textAlign: 'center',
    },
    clinicAreasCount: {
        fontSize: 12,
        color: '#6B7280',
        backgroundColor: '#F3F4F6',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 4,
        alignSelf: 'flex-start', // Para que no ocupe toda la línea
    },
    infoCard: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginVertical: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    infoGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    infoItem: {
        marginBottom: 5,
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 5,
    },
    infoValueBox: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    infoValue: {
        fontSize: 16,
        color: '#111827',
        fontWeight: '500',
    },
    responsableInput: {
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        padding: 5,
        fontSize: 16,
        color: '#111827',
        marginLeft: 10,
        flex: 1,
    },
    sucursalDisplay: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    sucursalText: {
        flex: 1,
        fontSize: 16,
        color: '#111827',
        marginLeft: 10,
        marginRight: 10,
    },
    progressCard: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginBottom: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    progressHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    progressLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
    },
    progressPercentage: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    progressBar: {
        height: 10,
        backgroundColor: '#e5e7eb',
        borderRadius: 5,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        borderRadius: 5,
    },
    progressFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    progressStatus: {
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 8,
    },
    areaSection: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginBottom: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    areaHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
    },
    cameraButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#05aaca',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 8,
    },
    cameraButtonText: {
        color: 'white',
        fontWeight: '600',
        marginLeft: 8,
        fontSize: 14,
    },
    areaScroll: {
        maxHeight: 100,
        minHeight: 50,
    },
    areaButton: {
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        paddingHorizontal: 8,
        paddingVertical: 8,
        borderRadius: 10,
        marginRight: 5,
        width: 100,
        position: 'relative',
    },
    areaButtonActive: {
        backgroundColor: '#ff006f',
    },
    areaIcon: {
        fontSize: 24,
        marginBottom: 5,
    },
    areaButtonText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#374151',
        textAlign: 'center',
    },
    areaButtonTextActive: {
        color: 'white',
        fontWeight: 'bold',
    },
    areaBadge: {
        position: 'absolute',
        top: 1,
        right: 1,
        backgroundColor: '#10b981',
        borderRadius: 10,
        borderColor: 'white',
        borderWidth: 1,
        minWidth: 30,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 5,
    },
    areaBadgeText: {
        color: 'white',
        fontSize: 10,
        fontWeight: 'bold',
    },
    photosSection: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginBottom: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    photosHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    photosCount: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '600',
    },
    photoCard: {
        position: 'relative',
        marginRight: 12,
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 8,
        width: 140,
    },
    photo: {
        width: 120,
        height: 120,
        borderRadius: 6,
    },
    deleteButton: {
        position: 'absolute',
        top: 5,
        right: 5,
        backgroundColor: 'red',
        borderRadius: 15,
        width: 30,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    photoInfo: {
        marginTop: 8,
    },
    photoDescription: {
        fontSize: 11,
        color: '#6b7280',
        marginBottom: 4,
    },
    photoTimestamp: {
        fontSize: 10,
        color: '#9ca3af',
        fontStyle: 'italic',
    },
    evaluationSection: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginBottom: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    evaluationHeader: {
        marginBottom: 5,
    },
    evaluationSubtitle: {
        fontSize: 14,
        color: '#6b7280',
    },
    itemCard: {
        backgroundColor: '#f4f4f5',
        padding: 8,
        borderRadius: 10,
        marginBottom: 5,
    },
    itemText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 5,
    },
    ratingContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    ratingButton: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 8,
        borderRadius: 8,
        marginHorizontal: 4,
        borderWidth: 1,
        borderColor: '#d1d5db',
        justifyContent: 'center',
    },
    radioCircle: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#d1d5db',
        marginRight: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    radioInner: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    ratingText: {
        fontSize: 12,
        fontWeight: 'bold',
    },
    observationsInput: {
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        padding: 10,
        fontSize: 14,
        minHeight: 40,
        backgroundColor: 'white',
        textAlignVertical: 'top',
    },
    commentsSection: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginBottom: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    commentsInput: {
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        padding: 15,
        fontSize: 16,
        minHeight: 120,
        textAlignVertical: 'top',
        backgroundColor: 'white',
    },
    actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: 15,
        marginBottom: 15,
        gap: 10,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    saveButton: {
        backgroundColor: '#ff006f',
    },
    newButton: {
        backgroundColor: '#8f5c03',
    },
    actionButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    footer: {
        padding: 5,
        alignItems: 'center',
    },
    footerText: {
        fontSize: 12,
        color: '#6B7280',
        textAlign: 'center',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 8,
        width: '90%',
        maxWidth: 400,
    },
    previewImage: {
        width: '100%',
        height: 250,
        borderRadius: 8,
        marginBottom: 5,
    },
    descriptionInput: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        padding: 8,
        fontSize: 16,
        marginBottom: 5,
        minHeight: 40,
        textAlignVertical: 'top',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 5,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 15,
        borderRadius: 8,
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: '#e72525',
    },
    savePhotoButton: {
        backgroundColor: '#05aaca',
    },
    cancelButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    savePhotoButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    areasCountBox: {
        backgroundColor: '#f8f9fa',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    areasCountText: {
        fontSize: 14,
        color: '#3B82F6',
        fontWeight: '500',
    },
    areasCountInfo: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 2,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#374151',
        marginBottom: 8,
        textAlign: 'center',
    },
    // Indicador de progreso en el header
    completionIndicator: {
        marginTop: 5,
        width: '100%',
        alignItems: 'center',
        backgroundColor: 'white',
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    completionText: {
        fontSize: 12,
        color: '#6b7280',
        marginBottom: 5,
        fontWeight: '500',
    },
    completionBar: {
        width: '80%',
        height: 6,
        backgroundColor: '#d5d6d8',
        borderRadius: 3,
        overflow: 'hidden',
    },
    completionFill: {
        height: '100%',
        borderRadius: 3,
    },
    // Estilos para el modal de validación
    validationModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 8,
    },
    validationModalContent: {
        backgroundColor: 'white',
        borderRadius: 15,
        width: '100%',
        height: '70%',
        maxWidth: 400,
        maxHeight: '90%',
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    validationHeader: {
        alignItems: 'center',
        marginBottom: 10,
    },
    validationTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#374151',
        marginTop: 10,
        marginBottom: 5,
    },
    validationSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
    },
    incompleteAreasList: {
        maxHeight: 300,
        marginBottom: 10,
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 8,
        borderWidth: 1,
        borderColor: '#a7aab0bb',
    },
    incompleteAreaItem: {
        backgroundColor: '#F9FAFB',
        borderRadius: 10,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    areaItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
    },
    areaItemNumber: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#05aaca',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    areaNumberText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 14,
    },
    areaItemInfo: {
        flex: 1,
    },
    areaItemName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 2,
    },
    areaItemAction: {
        fontSize: 12,
        color: '#6B7280',
    },
    validationButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 5,
        marginBottom: 10,
    },
    validationButton: {
        flex: 1,
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    cancelValidationButton: {
        backgroundColor: '#e72525',
    },
    cancelValidationButtonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 14,
    },
    forceSaveButton: {
        backgroundColor: '#05aaca',
    },
    forceSaveButtonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 14,
        margin: 5,
    },
    validationNote: {
        fontSize: 12,
        color: '#6B7280',
        textAlign: 'center',
        fontStyle: 'italic',
        marginTop: 10,
    },
    // Espacio extra al final del scroll
    bottomSpacer: {
        height: 50,
    },
    headerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#05aaca',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 8,
    },
    noAreasContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    noAreasTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#374151',
        marginTop: 16,
        marginBottom: 8,
    },
    noAreasText: {
        fontSize: 16,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
    },
    refreshButton: {
        backgroundColor: '#3B82F6',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 8,
    },
    refreshButtonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 16,
    },
    loadingOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContent: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 15,
        width: '80%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    loadingTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#05aaca',
        marginBottom: 20,
    },
    loadingText: {
        marginTop: 15,
        fontSize: 14,
        color: '#333',
        textAlign: 'center',
    },
    progressBarContainer: {
        width: '100%',
        height: 8,
        backgroundColor: '#e0e0e0',
        borderRadius: 4,
        marginTop: 15,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#05aaca',
        borderRadius: 4,
    },
    progressText: {
        marginTop: 8,
        fontSize: 14,
        fontWeight: '600',
        color: '#05aaca',
    },
    progressDetail: {
        marginTop: 5,
        fontSize: 12,
        color: '#666',
        fontStyle: 'italic',
    },
    circularProgressText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#05aaca',
    },
    stepContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        marginBottom: 15,
    },
    stepIndicator: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#e0e0e0',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stepCompleted: {
        backgroundColor: '#10b981',
    },
    stepActive: {
        backgroundColor: '#05aaca',
    },
    stepNumber: {
        color: '#666',
        fontSize: 14,
        fontWeight: '600',
    },
    stepContent: {
        flex: 1,
    },
    stepLabel: {
        fontSize: 14,
        color: '#999',
    },
    stepLabelCompleted: {
        color: '#10b981',
        fontWeight: '500',
        textDecorationLine: 'line-through',
    },
    stepLabelActive: {
        color: '#05aaca',
        fontWeight: '600',
    },
    stepProgress: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    saveProgressButton: {
        backgroundColor: '#10B981',
    },
    progressIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 8,
    },
    progressDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 4,
    },
    progressDotActive: {
        backgroundColor: '#10B981',
    },
    progressDotInactive: {
        backgroundColor: '#D1D5DB',
    },
    uploadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
    },
    syncedBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 4,
    },
    lastSavedContainer: {
        paddingHorizontal: 16,
        paddingVertical: 4,
        backgroundColor: '#f0f9ff',
    },
    lastSavedText: {
        fontSize: 8,
        color: 'white',
        textAlign: 'left',
        marginLeft: 8,
    },
});