import { StyleSheet } from "react-native";

export const stylesmainMenu = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        marginBottom: 40,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 5,
        paddingLeft: 5,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    logo: {
        width: 80,
        height: 80,
        borderRadius: 12,
        margin: -5
    },
    headerText: {
        flexDirection: 'column',
        flex: 1,
        padding: 20,
        fontSize: 22,
        fontWeight: 'bold',
        color: '#000000'
    },
    nameVersion: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        flex: 1,
        paddingRight: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        marginHorizontal: 5,
    },
    appName: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#333',
    },
    appVersion: {
        fontSize: 14,
        color: '#666',
    },
    menuContainer: {
        flex: 1,
        padding: 10,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    menuCard: {
        width: '48%',
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        marginBottom: 16,
        alignItems: 'center',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    iconContainer: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    badge: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: '#FF5722',
        width: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    menuTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
        textAlign: 'center',
    },
    menuDescription: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
        lineHeight: 16,
    },
    footer: {
        padding: 12,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        alignItems: 'center',
    },
    footerText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
    },
    // Ajustar el contenido del botón en el header también
    clinicSelectorButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: 'white',
        borderColor: '#05aaca',
        paddingHorizontal: 5,
        paddingVertical: 2,
        borderRadius: 10,
        borderWidth: 1,
        marginHorizontal: 2,
    },
    clinicName: {
        fontSize: 16,
        color: '#05aaca',
        fontWeight: '600',
        marginLeft: 8,
        marginRight: 5,
        maxWidth: 220,
        flexShrink: 1, // Permite que se reduzca si es necesario
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    // También podemos ajustar el modal para más espacio
    clinicModalContent: {
        backgroundColor: 'white',
        borderRadius: 15,
        padding: 8, // Aumentado el padding
        width: '90%',
        maxWidth: 400,
        maxHeight: '80%', // Limitar altura máxima
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 10,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#374151',
        marginBottom: 8,
        textAlign: 'center',
    },
    clinicOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 15,
        marginBottom: 10,
        backgroundColor: '#f8f9fa',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: 'transparent',
        minHeight: 70, // Aumentamos la altura mínima
    },
    clinicOptionSelected: {
        backgroundColor: '#EFF6FF',
        borderColor: '#05aaca',
    },
    clinicOptionContent: {
        flexDirection: 'row',
        alignItems: 'flex-start', // Cambiado de 'center' a 'flex-start'
        flex: 1,
    },
    clinicTextContainer: {
        flex: 1,
        marginLeft: 12,
        justifyContent: 'center', // Para alinear verticalmente
    },
    clinicOptionText: {
        fontSize: 15,
        color: '#374151',
        fontWeight: '500',
        marginBottom: 4, // Espacio entre nombre y contador
    },
    clinicOptionTextSelected: {
        color: '#05aaca',
        fontWeight: 'bold',
    },
    clinicIconContainer: {
        width: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkIconContainer: {
        marginLeft: 8,
    },
    // Para el botón de cerrar
    modalCloseButton: {
        marginTop: 24,
        backgroundColor: '#e72525',
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    modalCloseButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    clinicSection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 5,
    },
    locationButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    clinicButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    locationInfoButton: {
        padding: 2,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    detectLocationModalButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: '#F0F9FF',
        borderRadius: 8,
        gap: 6,
    },
    detectLocationText: {
        color: '#05aaca',
        fontSize: 12,
        fontWeight: '600',
    },
    nearbyBadge: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#05aaca',
        backgroundColor: '#D1FAE5',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        marginTop: 2,
        alignSelf: 'flex-start',
    },
    loadingOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContent: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 12,
        alignItems: 'center',
        width: '80%',
    },
    loadingText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginTop: 16,
        textAlign: 'center',
    },
});