import { StyleSheet } from "react-native";

export const stylesreminders = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        paddingHorizontal: 5,
        paddingVertical: 5,
        marginTop: -30,
    },
    backButton: {
        backgroundColor: '#ff006f',
        padding: 8,
        borderRadius: 8,
    },
    title: {
        flex: 1,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginLeft: 16,
    },
    // ESTILOS NUEVOS PARA LA CLÍNICA
    clinicaBadge: {
        backgroundColor: '#2196F3',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
        marginBottom: 20,
    },
    clinicaBadgeText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    // FIN ESTILOS CLÍNICA
    
    clearButton: {
        flex: 1,
        alignItems: 'center',
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    emptyTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#666',
        marginTop: 16,
        marginBottom: 8,
    },
    emptyDescription: {
        fontSize: 16,
        color: '#999',
        textAlign: 'center',
        marginBottom: 32,
    },
    templateInfo: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
        marginTop: 20,
        paddingHorizontal: 20,
        fontStyle: 'italic',
    },
    emptyButtons: {
        width: '100%',
        alignItems: 'center',
        gap: 16,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2196F3',
        width: '80%',
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 12,
        elevation: 3,
    },
    actionButtonSecondary: {
        backgroundColor: '#4CAF50',
    },
    actionButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 12,
    },
    mainContent: {
        flex: 1,
        flexDirection: 'row',
    },
    sidebar: {
        width: '35%',
        backgroundColor: '#fff',
        borderRightWidth: 1,
        borderRightColor: '#e0e0e0',
    },
    statsContainer: {
        flexDirection: 'row',
        padding: 10,
        backgroundColor: '#f8f9fa',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        alignItems: 'center',
        elevation: 2,
    },
    statItem: {
        flex: 1,
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    statEnviados: {
        color: '#4CAF50',
    },
    statPendientes: {
        color: '#FF9800',
    },
    statLabel: {
        fontSize: 12,
        color: '#666',
        marginTop: 4,
    },
    actionButtons: {
        flexDirection: 'row',
        padding: 12,
        gap: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    sidebarButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2196F3',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        gap: 6,
    },
    sidebarButtonSecondary: {
        backgroundColor: '#4CAF50',
    },
    sidebarButtonText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '600',
    },
    clientesList: {
        flex: 1,
        backgroundColor: '#666',
    },
    clientesListContent: {
        paddingBottom: 20,
    },
    clienteItem: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f5f5f5',
        borderRadius: 10,
    },
    clienteItemSelected: {
        backgroundColor: '#05aaca',
    },
    clienteEnviado: {
        opacity: 0.7,
    },
    clienteItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    clienteIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    iconPendiente: {
        backgroundColor: '#424242',
    },
    iconEnviado: {
        backgroundColor: '#4CAF50',
    },
    clienteInfo: {
        flex: 1,
    },
    clienteNombre: {
        fontSize: 14,
        fontWeight: '600',
        color: '#ffffff',
    },
    clienteTelefono: {
        fontSize: 12,
        color: '#ffffff',
        marginTop: 2,
    },
    clienteMascotas: {
        fontSize: 10,
        color: '#ffffff',
        marginTop: 2,
        fontStyle: 'italic',
    },
    clienteCita: {
        fontSize: 10,
        color: '#90CAF9',
        marginTop: 2,
        fontStyle: 'italic',
    },
    messagesArea: {
        flex: 1,
        backgroundColor: '#666',
    },
    selectedClientInfo: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        backgroundColor: '#3b3b3b',
        borderRadius: 10,
    },
    selectedClientName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
    },
    selectedClientPhone: {
        fontSize: 14,
        color: 'white',
        marginTop: 4,
    },
    selectedClientPets: {
        fontSize: 13,
        color: 'white',
        marginTop: 4,
        fontStyle: 'italic',
    },
    selectedClientRecordatorios: {
        fontSize: 11,
        color: '#4CAF50',
        marginTop: 2,
        fontStyle: 'italic',
    },
    messagesContainer: {
        flex: 1,
        borderRadius: 10,
        backgroundColor: '#0000007b',
    },
    messagesContent: {
        padding: 16,
        paddingBottom: 100,
        borderRadius: 10,
    },
    sendButtonContainer: {
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        padding: 5,
        borderRadius: 10,
    },
    sendButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ff006f',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 10,
        elevation: 2,
    },
    sendButtonDisabled: {
        backgroundColor: '#4CAF50',
    },
    sendButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 12,
    },
    sendInstructions: {
        fontSize: 12,
        color: 'white',
        textAlign: 'center',
        marginTop: 8,
        fontStyle: 'italic',
    },
    noSelection: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    noSelectionText: {
        fontSize: 16,
        color: '#999',
        textAlign: 'center',
        marginTop: 16,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255,255,255,0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        fontSize: 16,
        color: '#333',
        marginTop: 16,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    templateSelector: {
        backgroundColor: '#fff',
        borderRadius: 12,
        width: '90%',
        maxHeight: '80%',
        padding: 16,
    },
    selectorHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    selectorTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    templateOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    templateOptionSelected: {
        backgroundColor: '#F5F9FF',
        borderLeftWidth: 3,
        borderLeftColor: '#2196F3',
    },
    templateOptionIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#2196F3',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    templateIconVacunas: {
        backgroundColor: '#4CAF50',
    },
    templateIconCitas: {
        backgroundColor: '#FF9800',
    },
    templateIconPersonalizado: {
        backgroundColor: '#9C27B0',
    },
    templateOptionInfo: {
        flex: 1,
    },
    templateOptionName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    templateOptionDesc: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    templateOptionFields: {
        fontSize: 11,
        color: '#888',
        marginTop: 2,
    },
    configTemplateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2196F3',
        padding: 12,
        borderRadius: 8,
        marginTop: 16,
    },
    configTemplateButtonDisabled: {
        backgroundColor: '#BDBDBD',
    },
    configTemplateButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    selectedTemplateBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E3F2FD',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 20,
        marginTop: 8,
        borderWidth: 1,
        borderColor: '#90CAF9',
    },
    selectedTemplateText: {
        color: '#1565C0',
        fontSize: 14,
        fontWeight: '600',
        marginRight: 4,
    },
    citaInfo: {
        marginTop: 8,
        backgroundColor: '#e3f2fd',
        padding: 8,
        borderRadius: 8,
    },
    citaInfoItem: {
        fontSize: 12,
        color: '#1976d2',
        marginVertical: 2,
    },
    // ESTILOS PARA INFORMACIÓN DE TEMPLATE
    templateHeader: {
        padding: 12,
        backgroundColor: '#F8F9FA',
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
        alignItems: 'center',
    },
    templateCurrent: {
        fontSize: 14,
        color: '#666',
        fontWeight: '600',
    },
    templateName: {
        fontSize: 16,
        color: '#2196F3',
        fontWeight: 'bold',
        marginTop: 4,
    },
    // ESTILOS PARA ENCABEZADOS DE TEMPLATE
    templateHeadersInfo: {
        padding: 12,
        backgroundColor: '#FFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    templateHeadersTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
    },
    templateHeaderItem: {
        flexDirection: 'row',
        marginBottom: 4,
    },
    templateHeaderName: {
        fontSize: 12,
        color: '#666',
        fontWeight: '600',
        width: 120,
    },
    templateHeaderDesc: {
        fontSize: 12,
        color: '#888',
        flex: 1,
    },
    // ESTILOS PARA BOTÓN DE CAMBIAR TEMPLATE
    changeTemplateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFF',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#2196F3',
        marginTop: 8,
    },
    changeTemplateButtonText: {
        color: '#2196F3',
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 6,
    },
    // ESTILOS PARA INDICADOR DE FORMATO
    formatInfo: {
        padding: 16,
        backgroundColor: '#FFF3CD',
        borderWidth: 1,
        borderColor: '#FFEEBA',
        borderRadius: 8,
        marginHorizontal: 16,
        marginTop: 8,
    },
    formatTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#856404',
        marginBottom: 8,
    },
    formatItem: {
        fontSize: 12,
        color: '#856404',
        marginBottom: 4,
    },
    formatRequired: {
        fontWeight: 'bold',
    },
    formatOptional: {
        fontStyle: 'italic',
    },
});